data:
  adapt_pt_dir: "pts/adapt"
  adapt_csv: "resource/dataset_split_2018_2024/adapt_2023.csv"

model:
  fusion_mode: concat

train:
  exp_name: continual_b1_i1_adapt_100
  epochs: 70
  historical_epochs: 60
  adaptation_epochs: 10
  adaptation_ratio: 1.00
  replay_ratio: 0.25
  replay_strategy: static

