class ArchitectureConstants:
    HEAD_HIDDEN_DIMS = [256, 128]
    HEAD_DROPOUT_RATES = [0.3, 0.2]
    HEAD_DROPOUT = 0.2

    GATE_HIDDEN_DIM = 128
    GATE_INIT_BIAS = 0.0
    GATE_JOINT_INIT_BIAS = 0.5

    MODALITY_ALIVE_THRESHOLD = 0.01


class QualityConstants:
    API_COUNT_NORM = 128.0
    API_DIVERSITY_SCALE = 2.0
    API_COUNT_WEIGHT = 0.35
    API_DIVERSITY_WEIGHT = 0.25
    API_COVERAGE_WEIGHT = 0.25
    API_TYPE_WEIGHT = 0.15

    GRAPH_NODE_NORM = 32.0
    GRAPH_NODE_WEIGHT = 0.35
    GRAPH_EDGE_WEIGHT = 0.35
    GRAPH_FEATURE_WEIGHT = 0.30

    ALIGN_NODE_COVER_WEIGHT = 0.5
    ALIGN_API_COVER_WEIGHT = 0.5

class GateConstants:
    NUM_BRANCHES = 4
    UNIFORM_BRANCH_WEIGHT = 0.25
    EPS = 1e-8


class EvidenceIndex:
    Q_ALIGN = 0
    R_API = 1
    R_GRAPH = 2
    R_MANIFEST = 3
    API_CONFIDENCE = 4
    GRAPH_CONFIDENCE = 5
    MANIFEST_CONFIDENCE = 6
    JOINT_CONFIDENCE = 7
    API_GRAPH_DISAGREEMENT = 8
    API_GRAPH_CONSISTENCY = 9
    API_MANIFEST_CONSISTENCY = 10
    GRAPH_MANIFEST_CONSISTENCY = 11
    API_ALIVE = 12
    GRAPH_ALIVE = 13
    MANIFEST_ALIVE = 14
    MANIFEST_TO_CODE_CONFLICT = 15
    CODE_TO_MANIFEST_CONFLICT = 16

    BASE_DIM = 17
    PERT_API = 17
    PERT_GRAPH = 18
    PERT_MANIFEST = 19
    WITH_PERTURBATION_DIM = 20
