data:
  adapt_pt_dir: "/pts/test"
  adapt_csv: "results/labels/test_2023.csv"

model:
  fusion_mode: concat

train:
  exp_name: i1_adapt_020_no_replay
  epochs: 70
  historical_epochs: 60
  adaptation_epochs: 10
  adaptation_ratio: 0.20
  replay_ratio: 0.0
  replay_strategy: static

