data:
  adapt_pt_dir: "/pts/test"
  adapt_csv: "results/labels/test_2023.csv"

model:
  fusion_mode: concat

train:
  exp_name: i1_ratio_100_dynamic_replay
  epochs: 70
  historical_epochs: 60
  adaptation_epochs: 10
  adaptation_ratio: 1.00
  replay_ratio: 0.25
  replay_strategy: dynamic_year_class

